import React from "react";

export default function AvatarSelector({ avatar, onChange, pathPrefix = "", style = ""}) {
    const avatarOptions = [
        "../images/user_profile_icon/baby_chick_1.png",
        "../images/user_profile_icon/badger_1.png",
        "../images/user_profile_icon/bat_1.png",
        "../images/user_profile_icon/bear_1.png",
        "../images/user_profile_icon/beaver_1.png",
        "../images/user_profile_icon/bird_1.png",
        "../images/user_profile_icon/bison_1.png",
        "../images/user_profile_icon/boar_1.png",
        "../images/user_profile_icon/boy_1.png",
        "../images/user_profile_icon/boy_2.png",
        "../images/user_profile_icon/boy_3.png",
        "../images/user_profile_icon/boy_4.png",
        "../images/user_profile_icon/camel_1.png",
        "../images/user_profile_icon/camel_2.png",
        "../images/user_profile_icon/cat_1.png",
        "../images/user_profile_icon/cat_2.png",
        "../images/user_profile_icon/cat_3.png",
        "../images/user_profile_icon/chicken_1.png",
        "../images/user_profile_icon/child_1.png",
        "../images/user_profile_icon/child_2.png",
        "../images/user_profile_icon/child_3.png",
        "../images/user_profile_icon/child_4.png",
        "../images/user_profile_icon/child_5.png",
        "../images/user_profile_icon/child_6.png",
        "../images/user_profile_icon/chipmunk_1.png",
        "../images/user_profile_icon/cow_1.png",
        "../images/user_profile_icon/crocodile_1.png",
        "../images/user_profile_icon/deer_1.png",
        "../images/user_profile_icon/default_user.png",
        "../images/user_profile_icon/dodo_1.png",
        "../images/user_profile_icon/dog_1.png",
        "../images/user_profile_icon/dog_2.png",
        "../images/user_profile_icon/dog_3.png",
        "../images/user_profile_icon/dolphin_1.png",
        "../images/user_profile_icon/donkey_1.png",
        "../images/user_profile_icon/dove_1.png",
        "../images/user_profile_icon/dragon_1.png",
        "../images/user_profile_icon/dragon_2.png",
        "../images/user_profile_icon/eagle_1.png",
        "../images/user_profile_icon/elephant_1.png",
        "../images/user_profile_icon/ewe_1.png",
        "../images/user_profile_icon/flamingo_1.png",
        "../images/user_profile_icon/fox_1.png",
        "../images/user_profile_icon/frog_1.png",
        "../images/user_profile_icon/giraffe_1.png",
        "../images/user_profile_icon/goat_1.png",
        "../images/user_profile_icon/hamster_1.png",
        "../images/user_profile_icon/hatching_chick_1.png",
        "../images/user_profile_icon/hedgehog_1.png",
        "../images/user_profile_icon/hippopotamus_1.png",
        "../images/user_profile_icon/horse_1.png",
        "../images/user_profile_icon/horse_2.png",
        "../images/user_profile_icon/kangaroo_1.png",
        "../images/user_profile_icon/koala_1.png",
        "../images/user_profile_icon/leopard_1.png",
        "../images/user_profile_icon/lion_1.png",
        "../images/user_profile_icon/lizard_1.png",
        "../images/user_profile_icon/llama_1.png",
        "../images/user_profile_icon/mammoth_1.png",
        "../images/user_profile_icon/monkey_1.png",
        "../images/user_profile_icon/monkey_2.png",
        "../images/user_profile_icon/monkey_3.png",
        "../images/user_profile_icon/monkey_4.png",
        "../images/user_profile_icon/moose_1.png",
        "../images/user_profile_icon/mouse_1.png",
        "../images/user_profile_icon/otter_1.png",
        "../images/user_profile_icon/owl_1.png",
        "../images/user_profile_icon/ox_1.png",
        "../images/user_profile_icon/panda_1.png",
        "../images/user_profile_icon/parrot_1.png",
        "../images/user_profile_icon/peacock_1.png",
        "../images/user_profile_icon/penguin_1.png",
        "../images/user_profile_icon/person_1.png",
        "../images/user_profile_icon/person_2.png",
        "../images/user_profile_icon/person_3.png",
        "../images/user_profile_icon/person_4.png",
        "../images/user_profile_icon/phoenix_bird_1.png",
        "../images/user_profile_icon/pig_1.png",
        "../images/user_profile_icon/pig_2.png",
        "../images/user_profile_icon/polar_bear_1.png",
        "../images/user_profile_icon/rabbit_1.png",
        "../images/user_profile_icon/rabbit_2.png",
        "../images/user_profile_icon/raccoon_1.png",
        "../images/user_profile_icon/ram_1.png",
        "../images/user_profile_icon/rhinoceros_1.png",
        "../images/user_profile_icon/sauropod_1.png",
        "../images/user_profile_icon/seal_1.png",
        "../images/user_profile_icon/skunk_1.png",
        "../images/user_profile_icon/sloth_1.png",
        "../images/user_profile_icon/snake_1.png",
        "../images/user_profile_icon/spouting-whale_1.png",
        "../images/user_profile_icon/swan_1.png",
        "../images/user_profile_icon/t-rex_1.png",
        "../images/user_profile_icon/teacher_1.png",
        "../images/user_profile_icon/teacher_10.png",
        "../images/user_profile_icon/teacher_11.png",
        "../images/user_profile_icon/teacher_12.png",
        "../images/user_profile_icon/teacher_13.png",
        "../images/user_profile_icon/teacher_14.png",
        "../images/user_profile_icon/teacher_15.png",
        "../images/user_profile_icon/teacher_16.png",
        "../images/user_profile_icon/teacher_17.png",
        "../images/user_profile_icon/teacher_18.png",
        "../images/user_profile_icon/teacher_2.png",
        "../images/user_profile_icon/teacher_3.png",
        "../images/user_profile_icon/teacher_4.png",
        "../images/user_profile_icon/teacher_5.png",
        "../images/user_profile_icon/teacher_6.png",
        "../images/user_profile_icon/teacher_7.png",
        "../images/user_profile_icon/teacher_8.png",
        "../images/user_profile_icon/teacher_9.png",
        "../images/user_profile_icon/tiger_1.png",
        "../images/user_profile_icon/tiger_2.png",
        "../images/user_profile_icon/turtle_1.png",
        "../images/user_profile_icon/unicorn_1.png",
        "../images/user_profile_icon/water_buffalo_1.png",
        "../images/user_profile_icon/whale_1.png",
        "../images/user_profile_icon/wolf_1.png",
        "../images/user_profile_icon/woman_1.png",
        "../images/user_profile_icon/woman_2.png",
        "../images/user_profile_icon/woman_3.png",
        "../images/user_profile_icon/woman_4.png",
        "../images/user_profile_icon/woman_5.png",
        "../images/user_profile_icon/woman_6.png",
        "../images/user_profile_icon/woman_7.png",
        "../images/user_profile_icon/woman_8.png",
        "../images/user_profile_icon/zebra_1.png",
    ]

    return (
        <div className={`flex flex-wrap gap-3 max-h-55 overflow-y-auto p-5 mb-2 border rounded ${style}`}>
            {avatarOptions.map((a) => (
                <button
                    key={a}
                    type="button"
                    onClick={() => onChange(a)}
                    className={`
                        p-1 rounded-lg border
                        ${avatar === a ? "border-black" : "border-transparent"}
                        hover:border-blue-500 hover:scale-108
                        transition-all duration-200
                    `}
                >
                    <img 
                        src={pathPrefix + a}
                        alt="avatar option"
                        className="w-12 h-12 object-contain rounded"
                    />
                </button>
            ))}
        </div>
    )
};